from __future__ import annotations

import logging
import re
import warnings
from abc import ABC, abstractmethod
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Callable, Dict, List, NamedTuple, Optional, Tuple

from ..exceptions import ConfigurationError
from ..tools import parse_file
from ..tools.file_parser import (
    MARKDOWN_HEADING_RE as _MARKDOWN_HEADING_RE,
    PAGE_BREAK,
    SUPPORTED_SUFFIXES as _SUPPORTED_SUFFIXES,
    TABLE_MARKER_RE as _TABLE_MARKER_RE,
)
from .fusion import expand_query, reciprocal_rank_fusion
from .reranking import (
    _MAX_RERANK_CANDIDATE_K,
    _resolve_candidate_k,
    Reranker,
    resolve_reranker,
)
from .text_tokenize import significant_terms, tokenize
from .tool_context import add_usage, report_trace

_logger = logging.getLogger(__name__)

# Folder scanning discovers exactly what `parse_bytes` can dispatch on -- the
# same set `parse_file` supports, imported rather than copied so a suffix added
# to the parser is found here too, instead of silently not being. Re-exported
# under the old private name because `ui/backend/ingestion.py` imports it.

# Every parser in `bestteam.tools.file_parser` prefixes its output with a
# bracketed header line naming the document, and adds one per sheet/table
# inside it. Those lines are generated by us, not extracted from the document,
# so "the parsed string is non-empty" is not the same question as "the document
# had any text in it": a scanned PDF parses to `[PDF: scan.pdf -- 3 page(s)]`
# and nothing else, which chunks into a content-free chunk that matches
# nothing and tells nobody the pages were never read.
_PARSER_HEADER_RE = re.compile(r"^\[(?:PDF|Word|Excel|CSV|XML|Sheet|Table)[: ][^\n]*\]\s*$", re.M)

_NO_TEXT_MESSAGE = (
    "No text could be extracted from this file. If it is a scanned PDF it "
    "needs OCR, which isn't supported yet."
)


def _has_extractable_text(text: str) -> bool:
    """True when parsed `text` holds anything beyond the parser's own header
    lines -- i.e. the document actually contributed content."""
    return bool(_PARSER_HEADER_RE.sub("", text).strip())


def _unsupported_suffix_message(suffix: str) -> str:
    """The one wording both ingestion paths report for a file type neither
    `parse_file` nor `parse_bytes` can read."""
    supported = ", ".join(sorted(_SUPPORTED_SUFFIXES))
    return f"Unsupported file type '{suffix}'. Supported: {supported}"


def _require_bm25():
    """Check that rank_bm25 is available and return the BM25Okapi class.

    Raises ConfigurationError if the package is not installed.
    This check must run early to avoid expensive operations (like file parsing)
    before discovering a missing dependency.
    """
    try:
        from rank_bm25 import BM25Okapi
    except ImportError as exc:
        raise ConfigurationError(
            "Knowledge bases require the 'rank-bm25' package. "
            "Install it with: pip install 'bestteam[tools-rag]'"
        ) from exc
    return BM25Okapi


class KnowledgeBase(ABC):
    """A queryable source of client documents that agents can search.

    Implementations are responsible for ingesting documents from wherever
    they live and answering free-text queries with relevant excerpts.
    Retrieval (`search`) and presentation (`query`) are deliberately split:
    each subclass ranks chunks its own way, but every one of them is
    rendered by the single `format_results` below, so the string an agent
    sees -- and the citation tags it is told to quote -- cannot drift
    between knowledge base types.
    """

    name: str
    #: One sentence describing what these documents cover, shown to the model
    #: in the tool's own description. `None` for a knowledge base that was
    #: never given one.
    description: Optional[str] = None
    #: The ingestion job (content generation) every indexed chunk came from,
    #: when the chunks carry one and all agree -- the backend's DB-backed
    #: `from_chunks` path. `None` for a knowledge base built from a folder.
    #: Reported on the trace of every search, hits or not, so a run's record
    #: says which generation of a collection it was answered from.
    ingestion_job_id: Optional[int] = None

    @abstractmethod
    def search_hits(self, query: str, top_k: Optional[int] = None) -> List["RetrievalHit"]:
        """Return the chunks most relevant to the query, best first, each with
        the scores that put it there and the identity it carries."""

    def search(self, query: str, top_k: Optional[int] = None) -> List["_Chunk"]:
        """Return the chunks most relevant to the query, best first."""
        return [hit.chunk for hit in self.search_hits(query, top_k)]

    def query(self, query: str, top_k: Optional[int] = None) -> str:
        """Return formatted excerpts most relevant to the query."""
        return format_results(self.name, query, self.search(query, top_k))


class _Chunk(NamedTuple):
    """One indexed excerpt plus whatever location its format made exact.

    `page`/`heading` default to `None` so every pre-existing two-argument
    construction (and every `from_chunks` caller) keeps working: a chunk
    from a format that carries no page or section simply cites its filename,
    exactly as before.
    """

    source: str
    text: str
    page: Optional[int] = None
    heading: Optional[str] = None
    #: Opaque identity supplied by whoever built the chunks -- the backend's
    #: `knowledge_chunks` row, its document, and the ingestion job that wrote
    #: them. `None` on the SDK path (a folder has no rows). Never part of the
    #: citation the model sees; carried so a hit can be tied back to a row.
    chunk_id: Optional[int] = None
    document_id: Optional[int] = None
    ingestion_job_id: Optional[int] = None


class RetrievalHit(NamedTuple):
    """One search result: the chunk plus why it ranked where it did.

    `fused_score` is the reciprocal-rank-fusion score across every
    (query variant x retrieval leg) list the chunk appeared in -- the order
    candidates reach the reranker in. `leg_scores` is each retrieval leg's
    own raw score for the chunk (`"bm25"`: Okapi score; `"vector"`: cosine),
    keyed by leg name and keeping the best value across query variants, so
    its keys also say *which* leg surfaced the chunk. `rerank_score` is the
    cross-encoder's score when a reranker ran and succeeded; `None` when no
    reranker is configured or scoring failed and the retrieval order was
    kept -- a missing score is never faked.
    """

    chunk: _Chunk
    fused_score: float
    leg_scores: Dict[str, float]
    rerank_score: Optional[float] = None


def _generation_of(chunks: List[_Chunk]) -> Optional[int]:
    """The one `ingestion_job_id` every chunk carries, or `None` when any
    chunk has none or they disagree (a mixed list has no single generation)."""
    ids = {chunk.ingestion_job_id for chunk in chunks}
    if len(ids) == 1:
        return next(iter(ids))
    return None


def _tag_safe(text: str) -> str:
    """A citation cannot carry the character that ends its own tag.

    `]` closes `[source: …]`, so a filename or heading containing one cuts
    the tag short -- for a reader, and for `core/grounding.py`, which would
    then report a correct citation unverified and, under an agent's
    `refuse` grounding policy, refuse the answer over it.

    Only `]` breaks the tag, but the opening bracket is swapped with it so a
    section titled "Item [2]" still reads as "Item (2)" in an answer the
    customer sees, rather than as a half-closed "Item [2)".
    """
    return text.replace("[", "(").replace("]", ")")


def _citation_document(chunk: _Chunk) -> str:
    """The filename part of a chunk's citation, exactly as the model sees it.

    Reported alongside the full citations so the grounding check can verify a
    filename-only tag by set membership instead of splitting a label apart.
    """
    return _tag_safe(chunk.source)


def _citation(chunk: _Chunk) -> str:
    """The inside of a chunk's `[source: ...]` tag: its filename, then the
    page and section that narrow it down when the format supplied them."""
    citation = _citation_document(chunk)
    if chunk.page is not None:
        citation += f", p.{chunk.page}"
    if chunk.heading:
        citation += f" § {_tag_safe(chunk.heading)}"
    return citation


def format_results(kb_name: str, query: str, chunks: List[_Chunk]) -> str:
    """Render retrieved chunks as the string an agent's tool call returns.

    The one formatter for all three knowledge base types. Byte-for-byte
    identical to what each type rendered separately when no chunk carries a
    page or heading.
    """
    if not chunks:
        return f"No results found in knowledge base '{kb_name}' for: {query}"

    lines = [f"Knowledge base '{kb_name}' results for: {query}\n"]
    for i, chunk in enumerate(chunks, 1):
        lines.append(f"{i}. [source: {_citation(chunk)}]")
        lines.append(chunk.text.strip())
        lines.append("")
    return "\n".join(lines)


class LocalFolderKnowledgeBase(KnowledgeBase):
    """A knowledge base backed by a folder of documents on disk.

    Documents are parsed (via :func:`bestteam.tools.parse_file`), split into
    overlapping chunks, and indexed in memory with BM25 keyword search. This
    is intentionally lightweight — no embeddings, no vector store, no API
    keys — which suits the common case of a client handing over a folder
    with a handful to a couple dozen documents.
    """

    def __init__(
        self,
        name: str,
        path: str | Path,
        chunk_size: int = 1000,
        chunk_overlap: int = 100,
        top_k: int = 5,
        rerank_model: Any = None,
        candidate_k: Optional[int] = None,
        query_expansion_model: Any = None,
        query_expansion_count: int = 3,
        description: Optional[str] = None,
    ) -> None:
        _require_bm25()
        _validate_chunk_params(name, chunk_size, chunk_overlap)
        self.path = Path(path)
        chunks = _load_document_chunks(self.path, chunk_size, chunk_overlap)
        self._init_from_chunks(
            name, chunks, top_k,
            rerank_model=rerank_model,
            candidate_k=candidate_k,
            query_expansion_model=query_expansion_model,
            query_expansion_count=query_expansion_count,
            description=description,
        )

    @classmethod
    def from_chunks(
        cls,
        name: str,
        chunks: List["_Chunk"],
        top_k: int = 5,
        rerank_model: Any = None,
        candidate_k: Optional[int] = None,
        query_expansion_model: Any = None,
        query_expansion_count: int = 3,
        description: Optional[str] = None,
    ) -> "LocalFolderKnowledgeBase":
        """Build directly from pre-parsed chunks, skipping the file-parsing
        pipeline. Used by the backend's DB-backed ingestion path (see
        ui/backend/knowledge_bases.py) -- the SDK itself never touches a
        database; chunks are handed in as plain data."""
        self = cls.__new__(cls)
        self.path = None
        self._init_from_chunks(
            name, chunks, top_k,
            rerank_model=rerank_model,
            candidate_k=candidate_k,
            query_expansion_model=query_expansion_model,
            query_expansion_count=query_expansion_count,
            description=description,
        )
        return self

    def _init_from_chunks(
        self,
        name: str,
        chunks: List["_Chunk"],
        top_k: int,
        *,
        rerank_model: Any = None,
        candidate_k: Optional[int] = None,
        query_expansion_model: Any = None,
        query_expansion_count: int = 3,
        description: Optional[str] = None,
    ) -> None:
        BM25Okapi = _require_bm25()

        self.name = name
        self.description = description
        self.default_top_k = top_k
        self._reranker = resolve_reranker(rerank_model) if rerank_model is not None else None
        if candidate_k is not None and (candidate_k < top_k or candidate_k > _MAX_RERANK_CANDIDATE_K):
            raise ConfigurationError(
                f"Knowledge base '{name}': candidate_k ({candidate_k}) must be "
                f"between top_k ({top_k}) and {_MAX_RERANK_CANDIDATE_K}"
            )
        self._candidate_k = _resolve_candidate_k(candidate_k, top_k)
        self.query_expansion_model = query_expansion_model
        self.query_expansion_count = query_expansion_count

        self._chunks = list(chunks)
        if not self._chunks:
            raise ConfigurationError(
                f"Knowledge base '{name}' has no readable documents"
                + (f" in {self.path}" if self.path is not None else "")
            )
        self.ingestion_job_id = _generation_of(self._chunks)

        self._chunk_tokens = [tokenize(chunk.text) for chunk in self._chunks]
        self._chunk_terms = [significant_terms(tokens) for tokens in self._chunk_tokens]
        self._bm25 = BM25Okapi(self._chunk_tokens)

    def _bm25_leg(self, query_text: str, fetch_k: int) -> List[Tuple[int, float]]:
        """Identical scoring logic to the pre-refactor `query()` body,
        returning `(chunk index, BM25 score)` pairs, best first. The order is
        by shared-significant-term overlap first and BM25 score second; the
        score is carried for the hit's `leg_scores`, not for ordering."""
        query_tokens = tokenize(query_text)
        query_terms = significant_terms(query_tokens)
        scores = self._bm25.get_scores(query_tokens)

        matches = [
            (len(query_terms & chunk_terms), score, idx)
            for idx, (score, chunk_terms) in enumerate(zip(scores, self._chunk_terms))
            if query_terms & chunk_terms
        ]
        matches.sort(key=lambda m: (m[0], m[1]), reverse=True)
        return [(idx, float(score)) for _overlap, score, idx in matches[:fetch_k]]

    def search_hits(self, query: str, top_k: Optional[int] = None) -> List[RetrievalHit]:
        top_k = top_k or self.default_top_k
        variants = _query_variants(query, self.query_expansion_model, self.query_expansion_count)
        fetch_k = _rerank_fetch_k(top_k, self._candidate_k, self._reranker)
        candidates = _rrf_retrieve(variants, [("bm25", self._bm25_leg)], fetch_k)
        hits = [_hit_from_candidate(self._chunks, candidate) for candidate in candidates[:fetch_k]]
        return _rerank_candidates(query, hits, self._reranker, top_k)


_DEFAULT_SEPARATORS = ["\n\n", "\n", "。", "！", "？", ". ", " ", ""]

_MARKDOWN_SEPARATORS = ["\n# ", "\n## ", "\n### ", "\n#### ", "\n\n", "\n", "。", "！", "？", ". ", " ", ""]

# Separators that mark the START of the content they introduce (a heading
# line) rather than the END of what precedes them (like sentence-terminating
# punctuation) -- these get reattached as a prefix on the following piece;
# everything else is reattached as a suffix on the preceding piece.
_PREFIX_SEPARATORS = {"\n# ", "\n## ", "\n### ", "\n#### "}


# `.docx` joins `.md` here because `_parse_docx_bytes` now renders Word's
# heading styles as Markdown heading lines -- the same shape, so the same
# separators and the same `_headings_for` reader apply. It is only ever passed
# for a Word document's *prose*; a table block is split with the defaults, so a
# cell that happens to begin with `# ` can't become a heading boundary inside a
# run of rows.
_MARKDOWN_SUFFIXES = {".md", ".docx"}


def _separators_for_suffix(suffix: str) -> List[str]:
    return _MARKDOWN_SEPARATORS if suffix in _MARKDOWN_SUFFIXES else _DEFAULT_SEPARATORS


def _pack_pieces(pieces: List[str], chunk_size: int, fallback_separators: List[str]) -> List[str]:
    """Greedily merge adjacent pieces up to chunk_size; recurse into
    fallback_separators for any individual piece that's still too large on
    its own, folding whatever's accumulated in `current` (often a short
    heading/tag) into the text being split, so it always ends up packed
    with content rather than stranded as its own content-free chunk."""
    results: List[str] = []
    current = ""
    for piece in pieces:
        candidate = current + piece
        if len(candidate) <= chunk_size:
            current = candidate
        elif len(piece) > chunk_size:
            # Split `current + piece` as one text rather than `piece` alone,
            # so whatever's accumulated in `current` (often a short
            # heading/tag) gets packed together with as much of the
            # oversized piece as fits, instead of being left to fend for
            # itself as a separate, content-free chunk.
            sub = _recursive_split(current + piece, fallback_separators, chunk_size)
            results.extend(sub)
            current = ""
        else:
            if current:
                results.append(current)
            current = piece
    if current:
        results.append(current)
    return results


def _recursive_split(text: str, separators: List[str], chunk_size: int) -> List[str]:
    """Split text on the coarsest separator that fits chunk_size, recursing
    into finer separators only for pieces that are still too large."""
    if len(text) <= chunk_size:
        return [text] if text else []
    if not separators or separators[0] == "":
        # Last resort: no separator left to split on. Balance the split
        # evenly across the minimum number of chunks that fit chunk_size,
        # rather than greedily packing char-by-char at a fixed offset --
        # greedy fixed-size packing can strand a tiny (even single-character)
        # remainder as its own chunk, e.g. a lone trailing punctuation mark.
        length = len(text)
        num_chunks = -(-length // chunk_size)
        size = -(-length // num_chunks)
        return [text[i : i + size] for i in range(0, length, size)]

    sep, *rest = separators
    raw_pieces = text.split(sep)
    if sep in _PREFIX_SEPARATORS:
        # Re-attach the separator to every piece but the first, so a
        # piece that ends up starting its own chunk still carries its
        # own marker (e.g. a Markdown "## Heading") instead of silently
        # losing it.
        pieces = [raw_pieces[0]] + [sep + p for p in raw_pieces[1:]]
    else:
        # Suffix-style separators (sentence terminators, paragraph/line
        # breaks) end the piece before them, not start the piece after
        # -- re-attaching them as a prefix would strand a lone
        # punctuation mark as its own chunk when the split lands there.
        pieces = [p + sep for p in raw_pieces[:-1]] + [raw_pieces[-1]]
    return _pack_pieces(pieces, chunk_size, rest)


def _apply_overlap(pieces: List[str], chunk_overlap: int, chunk_size: int) -> List[str]:
    """Prepend each chunk (after the first) with up to chunk_overlap trailing
    characters of the previous chunk, capped so no chunk ever exceeds
    chunk_size -- the piece's own content is never trimmed, only how much
    cross-boundary context gets borrowed shrinks (down to zero) when a piece
    is already at or near chunk_size.

    Note: the borrowed prefix is a raw character slice, not separator-aware
    -- it can land mid-word/mid-tag/mid-heading. Structure-aware splitting
    (this module's main feature) applies to how chunks are cut, not to the
    overlap glued onto their boundaries."""
    if chunk_overlap <= 0 or len(pieces) <= 1:
        return pieces
    result = [pieces[0]]
    for prev, piece in zip(pieces, pieces[1:]):
        available = max(0, min(chunk_overlap, chunk_size - len(piece)))
        result.append(prev[-available:] + piece if available else piece)
    return result


def _split_pieces(text: str, chunk_size: int, suffix: str = "") -> List[str]:
    """The structure-aware split, before any overlap is glued on. Separate
    from `_chunk_text` so `_chunk_document` can read each piece's Markdown
    heading off text the previous chunk's borrowed tail hasn't shifted."""
    text = text.strip()
    if not text:
        return []
    pieces = _recursive_split(text, _separators_for_suffix(suffix), chunk_size)
    return [p for p in pieces if p.strip()]


def _chunk_text(text: str, chunk_size: int, chunk_overlap: int, suffix: str = "") -> List[str]:
    """Split text into chunks, preferring the document's own structure
    (paragraphs, sentences, words) over blind fixed-size character cuts."""
    return _apply_overlap(_split_pieces(text, chunk_size, suffix), chunk_overlap, chunk_size)


# `_MARKDOWN_HEADING_RE` is imported from `tools/file_parser.py`, which now
# *writes* this shape for a Word document's headings and has to escape any
# prose that would collide with it -- one definition, so the writer and the
# reader cannot disagree about what counts as a heading.

# A heading is a citation label, not an excerpt -- a pathological one-line
# "heading" shouldn't push the actual excerpt off the model's screen.
_MAX_HEADING_CHARS = 80


def _headings_for(pieces: List[str], start: Optional[str] = None) -> List[Optional[str]]:
    """The Markdown heading in effect at the start of each piece.

    Approximate by design, and Markdown-only. A piece the splitter cut at a
    heading boundary opens with its own heading and takes that; anything else
    inherits the last heading seen so far. Nothing here parses Markdown, so a
    `#` line inside a fenced code block reads as a heading, and a chunk that
    spans two sections is labelled with the one it starts in.

    `start` is the heading already in effect before the first piece. A Markdown
    document begins under none, but a Word document's prose is cut into
    segments by the tables between them, and the section a table interrupted is
    still the section the prose after it belongs to.
    """
    headings: List[Optional[str]] = []
    current: Optional[str] = start
    for piece in pieces:
        matches = list(_MARKDOWN_HEADING_RE.finditer(piece))
        # A parser-generated header line (`[Word: report.docx]`) is not content,
        # so it must not shadow the section the chunk actually opens under --
        # without this, a Word document's *first* section always lost its
        # heading, because that line is always in front of it.
        if matches and not _PARSER_HEADER_RE.sub("", piece[: matches[0].start()]).strip():
            current = matches[0].group(1)[:_MAX_HEADING_CHARS]
        headings.append(current)
        if matches:
            current = matches[-1].group(1)[:_MAX_HEADING_CHARS]
    return headings


# `_TABLE_MARKER_RE` is imported from `tools/file_parser.py`, which writes the
# bracketed line ahead of every block of CSV-style rows -- one per Excel sheet,
# one per Word table, one for a whole CSV file -- and escapes any of a
# document's own lines that would be read back as one. A `.csv` is a single
# block, so its own document header line is that block's marker rather than a
# second line above one.

# Formats whose parsed text is, or contains, such blocks.
_TABULAR_SUFFIXES = {".xlsx", ".xlsm", ".docx", ".csv"}


def _row_has_text(row: str) -> bool:
    """True when a CSV-style table row holds anything beyond its own commas.

    `read_only` openpyxl renders an empty row as its delimiters alone (`,,`),
    which survives `.strip()` but is not a row anybody can read. Deliberately
    local to the tabular path: `_has_extractable_text` answers a different
    question (did the *document* contribute anything) for every format.
    """
    return bool(row.replace(",", "").strip())


def _chunk_table_block(
    source: str, block: str, chunk_size: int, chunk_overlap: int, suffix: str
) -> List[_Chunk]:
    """Chunk one `[Sheet: ...]`/`[Table N]` block, repeating its marker line
    and header row at the top of every chunk it produces.

    The first body line with text in it is *assumed* to be the column header
    -- a heuristic. Leading rows that are empty once commas and whitespace are
    removed are skipped, because the spacer row so many workbooks put above
    their headers would otherwise be repeated instead of the headers. A table
    whose first real row is already data gets that row repeated, which wastes
    a little room but says nothing untrue.
    """
    stripped = block.strip()
    lines = stripped.split("\n")
    marker = lines[0]
    header_index = next((i for i in range(1, len(lines)) if _row_has_text(lines[i])), None)
    # A block with no readable row under its marker -- the trailing
    # `Sheet2`/`Sheet3` of a real workbook, a table that parsed to nothing, or
    # a formatted-but-empty sheet whose rows are bare commas -- is exactly the
    # content-free chunk P0-6 stopped indexing: it matches no query and reports
    # no problem, so it contributes nothing here either.
    if header_index is None:
        return []

    # Same 80-character cap as a Markdown heading: a sheet name is a citation
    # label, and a long one must not reach `_Chunk.heading` unbounded.
    heading = marker[1:-1][:_MAX_HEADING_CHARS]
    header_row = lines[header_index]
    prefix = marker + "\n" + header_row + "\n"
    body = "\n".join(lines[header_index + 1 :])

    # Repeat only when there is something to repeat over: a block that already
    # fits is one chunk, and a marker+header that leaves no room for a body
    # row would make `chunk_size - len(prefix)` zero or negative. Either way
    # the block goes through the ordinary path -- but still carries `heading`.
    if len(stripped) <= chunk_size or len(prefix) >= chunk_size:
        texts = _chunk_text(stripped, chunk_size, chunk_overlap, suffix)
    else:
        # `_apply_overlap` clamps the borrowed tail to the room left inside
        # the reduced size, so a long prefix quietly shrinks overlap towards
        # zero. Accepted: the repeated header is worth more than the overlap,
        # and the total still never exceeds `chunk_size`.
        texts = [
            prefix + piece
            for piece in _chunk_text(body, chunk_size - len(prefix), chunk_overlap, suffix)
        ]
    return [_Chunk(source=source, text=text, heading=heading) for text in texts]


def _trailing_heading(text: str, current: Optional[str]) -> Optional[str]:
    """The Markdown heading in effect *after* `text` -- what the next segment
    of a Word document's prose inherits across the table between them.

    Distinct from the last entry `_headings_for` returns, which is the heading
    in effect at the *start* of the final piece: a segment that opens under one
    section and introduces another must hand the later one on.
    """
    matches = list(_MARKDOWN_HEADING_RE.finditer(text))
    return matches[-1].group(1)[:_MAX_HEADING_CHARS] if matches else current


def _docx_segments(text: str) -> List[Tuple[bool, str]]:
    """Split parsed Word text into alternating prose and `[Table N]` blocks,
    as `(is_table, segment)` pairs in document order.

    A Word table block ends at the blank line `_parse_docx_bytes` puts after
    it. A spreadsheet's sheet block cannot be found that way -- `read_only`
    openpyxl renders an empty row as bare commas and a genuinely blank row as
    nothing, so a sheet legitimately contains blank lines a terminator would
    cut it at -- which is why only Word goes through here and a workbook still
    runs each marker to the next one.

    A marker line found *inside* a block already consumed is a table cell whose
    text happens to read `[Table 2]`, not a new table; it stays a row.
    """
    segments: List[Tuple[bool, str]] = []
    pos = 0
    for match in _TABLE_MARKER_RE.finditer(text):
        start = match.start()
        if start < pos:
            continue
        if start > pos:
            segments.append((False, text[pos:start]))
        blank = text.find("\n\n", start)
        pos = len(text) if blank == -1 else blank
        segments.append((True, text[start:pos]))
    if pos < len(text):
        segments.append((False, text[pos:]))
    return segments


def _chunk_docx_document(
    source: str, text: str, chunk_size: int, chunk_overlap: int, suffix: str
) -> List[_Chunk]:
    """Chunk a Word document, following its body order.

    Its tables are interleaved with its prose rather than appended after it, so
    the prose *between* two tables is real content that must chunk as prose --
    running each marker to the next one (what a spreadsheet does) would file
    those paragraphs under the preceding table's citation. Each prose segment
    is chunked on the Markdown separators the parser's heading lines create,
    carrying the section heading across the tables that interrupt it.
    """
    chunks: List[_Chunk] = []
    heading: Optional[str] = None
    for is_table, segment in _docx_segments(text):
        if is_table:
            # Deliberately not `suffix`: see `_MARKDOWN_SUFFIXES`.
            chunks.extend(_chunk_table_block(source, segment, chunk_size, chunk_overlap, ""))
            continue
        if not _has_extractable_text(segment):
            continue
        pieces = _split_pieces(segment, chunk_size, suffix)
        headings = _headings_for(pieces, heading)
        heading = _trailing_heading(segment, heading)
        texts = _apply_overlap(pieces, chunk_overlap, chunk_size)
        chunks.extend(
            _Chunk(source=source, text=piece, heading=piece_heading)
            for piece, piece_heading in zip(texts, headings)
        )
    return chunks


def _chunk_tabular_document(
    source: str, text: str, chunk_size: int, chunk_overlap: int, suffix: str
) -> List[_Chunk]:
    """Chunk a spreadsheet or a Word document, table block by table block.

    Packed through the generic path, a long table loses both its sheet/table
    name and its column header from the second chunk on: the rows survive but
    nothing says where they came from or what the columns mean, and the chunk
    cites the filename alone. Splitting on the parser's own marker lines fixes
    both -- every chunk is readable, searchable and citable on its own.
    """
    if suffix == ".docx":
        return _chunk_docx_document(source, text, chunk_size, chunk_overlap, suffix)

    starts = [match.start() for match in _TABLE_MARKER_RE.finditer(text)]
    chunks: List[_Chunk] = []

    # Whatever precedes the first marker: a Word document's body paragraphs
    # (real content, chunked the ordinary way) or a spreadsheet's `[Excel: ...]`
    # header line alone (nothing worth a chunk).
    preamble = text[: starts[0]] if starts else text
    if _has_extractable_text(preamble):
        chunks.extend(
            _Chunk(source=source, text=piece)
            for piece in _chunk_text(preamble, chunk_size, chunk_overlap, suffix)
        )

    for start, end in zip(starts, starts[1:] + [len(text)]):
        chunks.extend(
            _chunk_table_block(source, text[start:end], chunk_size, chunk_overlap, suffix)
        )
    return chunks


# The XML renderer (`tools/file_parser.py::_render_xml_tree`) emits one line
# per element -- `<tag attr="v"> text`, indented two spaces per level -- and a
# child's tail text as a line at the child's own depth. Indentation is
# therefore the element tree, and that is what the XML chunker reads.
def _xml_heading(element_line: str) -> str:
    """`<decision id="3" question="...">` -> `decision id="3" question="..."`.

    Attribute values are `quoteattr`-escaped by the renderer, so the first
    `>` is the end of the tag and nothing inside an attribute can fake it.
    """
    stripped = element_line.strip()
    end = stripped.find(">")
    inner = stripped[1:end] if end != -1 else stripped[1:]
    return inner[:_MAX_HEADING_CHARS]


def _xml_sections(
    indents: List[int], is_element: List[bool], start: int, end: int
) -> List[Tuple[int, int]]:
    """Group the items directly under one parent, as `[start, end)` line
    ranges: each section opens at a line at the shallowest depth present --
    a child element, which runs to the next item and owns everything deeper,
    or a line of the parent's own mixed-content text, which the renderer
    emits at the children's depth. The text line is its own section, not the
    tail of the child before it: it belongs to the parent, and must not be
    packed, prefixed or cited under that child's subtree."""
    level = min((indents[i] for i in range(start, end) if is_element[i]), default=None)
    if level is None:
        return [(start, end)]
    sections: List[Tuple[int, int]] = []
    section_start = start
    for i in range(start + 1, end):
        if indents[i] == level:
            sections.append((section_start, i))
            section_start = i
    sections.append((section_start, end))
    return sections


def _xml_path_prefix(ancestors: List[str], chunk_size: int) -> Tuple[str, int]:
    """The ancestor lines repeated at the top of a chunk, and how many of
    them were kept. Nearest first to be kept: the path is capped at half of
    `chunk_size`, outermost ancestors dropped first, so content always has
    at least half the chunk. Without the cap a six-level path in a small
    chunk left a few dozen characters for the leaves and shredded every one
    of them.
    """
    kept: List[str] = []
    total = 0
    for line in reversed(ancestors):
        total += len(line) + 1
        if total > chunk_size // 2:
            break
        kept.append(line)
    return "".join(line + "\n" for line in reversed(kept)), len(kept)


@dataclass
class _XmlLevel:
    """One level of the walk in `_xml_pieces`: the items directly under one
    parent, the path repeated above each chunk cut here, and the packing
    state. `kept` is how many of the innermost ancestors that path holds."""

    sections: List[Tuple[int, int]]
    prefix: str
    kept: int
    heading: Optional[str]
    next_index: int = 0
    current: str = ""


def _xml_pieces(lines: List[str], chunk_size: int) -> List[Tuple[str, Optional[str]]]:
    """Pack a rendered XML body into chunks of at most `chunk_size`,
    repeating the ancestor path at the top of every chunk.

    Sibling subtrees are packed greedily. A subtree too large to fit under
    its ancestors is opened up: its own element line joins the ancestor path
    and its children are packed one level down -- so a branch cut away from
    its decision still carries the decision, and the decisions above it, at
    the top of its chunk. A subtree with nothing deeper to split on (one
    oversized leaf), or whose own opening line is too long to be part of a
    path, falls back to the generic separators under the current path.

    The walk keeps its own stack rather than recursing, for the same reason
    the renderer does: a valid document can nest deeper than the Python
    call stack, and a chunk size large enough for every opener to head a
    path would otherwise descend one frame per level. Sections are line
    ranges, indents are measured once, and lengths are summed rather than
    joined until a body is actually cut -- re-reading the rest of a deep
    document at every level is quadratic.
    """
    indents = [len(line) - len(line.lstrip(" ")) for line in lines]
    is_element = [line.startswith("<", indent) for line, indent in zip(lines, indents)]
    pieces: List[Tuple[str, Optional[str]]] = []
    ancestors: List[str] = []
    # Per ancestor: has some chunk been cut with it in the repeated path? An
    # opener's attributes and inline text exist on that one line, and deeper
    # paths may be capped past it in every descendant chunk; one that was
    # never repeated is emitted as content at its own level when its subtree
    # is closed, packed with the siblings that follow.
    repeated: List[bool] = []
    half = chunk_size // 2

    def open_level(start: int, end: int) -> _XmlLevel:
        prefix, kept = _xml_path_prefix(ancestors, chunk_size)
        heading = _xml_heading(ancestors[-1]) if ancestors else None
        return _XmlLevel(_xml_sections(indents, is_element, start, end), prefix, kept, heading)

    def cut(level: _XmlLevel, body: str) -> None:
        pieces.append((level.prefix + body, level.heading))
        for i in range(len(ancestors) - level.kept, len(ancestors)):
            repeated[i] = True

    stack = [open_level(0, len(lines))]
    while stack:
        level = stack[-1]
        budget = chunk_size - len(level.prefix)
        if level.next_index == len(level.sections):
            if level.current:
                cut(level, level.current)
            stack.pop()
            if ancestors:
                opener = ancestors.pop()
                if not repeated.pop():
                    # The parent's `current` is empty: it was cut before
                    # this subtree was opened.
                    stack[-1].current = opener
            continue
        start, end = level.sections[level.next_index]
        level.next_index += 1
        body_len = sum(len(lines[i]) + 1 for i in range(start, end)) - 1
        if level.current and len(level.current) + 1 + body_len <= budget:
            level.current += "\n" + "\n".join(lines[start:end])
            continue
        if level.current:
            cut(level, level.current)
            level.current = ""
        if body_len <= budget:
            level.current = "\n".join(lines[start:end])
            continue
        opener = lines[start]
        # Descend only when the opener can head its children's path -- the
        # same cap `_xml_path_prefix` applies -- so a subtree is never split
        # into chunks that no longer say which element they belong to.
        if end - start > 1 and is_element[start] and len(opener) + 1 <= half:
            ancestors.append(opener)
            repeated.append(False)
            stack.append(open_level(start + 1, end))
            continue
        for piece in _recursive_split("\n".join(lines[start:end]), _DEFAULT_SEPARATORS, budget):
            if piece.strip():
                cut(level, piece)
    return pieces


def _chunk_xml_document(source: str, text: str, chunk_size: int) -> List[_Chunk]:
    """Chunk a rendered XML document along its element tree.

    A flowchart or decision tree exported as nested XML is only readable
    with its ancestry: `<branch answer="No">` means nothing without the
    question it answers and the branches above that. So every chunk repeats
    the element lines on the path from the root to its content -- the XML
    counterpart of the repeated sheet marker and header row in
    `_chunk_table_block` -- capped at half the chunk with the outermost
    dropped first, and cites the nearest one as its `heading`.

    There is no character overlap between XML chunks: the repeated path is
    the cross-chunk context, every split lands on a whole line, and a raw
    slice of the previous chunk would put a cut-open tag ahead of the path.
    The `[XML: name]` header line rides on the first chunk when there is
    room; it carries nothing the citation does not already say.
    """
    lines = text.strip().split("\n")
    header = lines[0] if lines and lines[0].startswith("[XML:") else None
    body = lines[1:] if header else lines
    if not any(line.strip() for line in body):
        return []
    pieces = _xml_pieces(body, chunk_size)
    if header and len(header) + 1 + len(pieces[0][0]) <= chunk_size:
        pieces[0] = (header + "\n" + pieces[0][0], pieces[0][1])
    return [_Chunk(source=source, text=piece, heading=heading) for piece, heading in pieces]


def _chunk_document(
    source: str, text: str, chunk_size: int, chunk_overlap: int, suffix: str = ""
) -> List[_Chunk]:
    """Chunk one parsed document, tagging each chunk with whatever location
    its format makes exact.

    A PDF is chunked **per page**, so no chunk straddles a page break and its
    `p.N` is precise. The cost is that a paragraph running across a page
    boundary loses the overlap it would otherwise borrow -- accepted, because
    a citation an operator can check beats an extra hundred characters of
    context. A `.xlsx`/`.xlsm`/`.docx`/`.csv` goes to `_chunk_tabular_document`,
    which splits on the parser's own `[Sheet: …]`/`[Table N]`/`[CSV: …]`
    markers and repeats the marker and header row in every chunk of an
    over-long block.
    An `.xml` goes to `_chunk_xml_document`, which splits along the element
    tree and repeats the ancestor path at the top of every chunk. Every
    other format is chunked exactly as before; `.md` chunks additionally
    carry the section heading they open under.
    """
    if suffix == ".pdf":
        chunks: List[_Chunk] = []
        for page, page_text in enumerate(text.split(PAGE_BREAK), start=1):
            chunks.extend(
                _Chunk(source=source, text=piece, page=page)
                for piece in _chunk_text(page_text, chunk_size, chunk_overlap, suffix=suffix)
            )
        return chunks

    if suffix in _TABULAR_SUFFIXES:
        return _chunk_tabular_document(source, text, chunk_size, chunk_overlap, suffix)

    if suffix == ".xml":
        return _chunk_xml_document(source, text, chunk_size)

    pieces = _split_pieces(text, chunk_size, suffix)
    headings = _headings_for(pieces) if suffix == ".md" else [None] * len(pieces)
    texts = _apply_overlap(pieces, chunk_overlap, chunk_size)
    return [
        _Chunk(source=source, text=piece, heading=heading)
        for piece, heading in zip(texts, headings)
    ]


def _validate_chunk_params(name: str, chunk_size: int, chunk_overlap: int) -> None:
    if chunk_size <= 0:
        raise ConfigurationError(
            f"Knowledge base '{name}': chunk_size must be positive, got {chunk_size}"
        )
    if chunk_overlap < 0 or chunk_overlap >= chunk_size:
        raise ConfigurationError(
            f"Knowledge base '{name}': chunk_overlap ({chunk_overlap}) must be "
            f"non-negative and less than chunk_size ({chunk_size})"
        )


def _load_document_chunks(path: Path, chunk_size: int, chunk_overlap: int) -> List[_Chunk]:
    chunks: List[_Chunk] = []
    for file_path in sorted(path.rglob("*")):
        if not file_path.is_file():
            continue
        suffix = file_path.suffix.lower()
        if suffix not in _SUPPORTED_SUFFIXES:
            warnings.warn(
                f"Skipping '{file_path}': {_unsupported_suffix_message(suffix)}",
                stacklevel=2,
            )
            continue
        try:
            text = parse_file(str(file_path))
        except ConfigurationError as exc:
            warnings.warn(f"Skipping unreadable file '{file_path}': {exc}", stacklevel=2)
            continue
        except Exception as exc:
            warnings.warn(f"Skipping unreadable file '{file_path}': {exc}", stacklevel=2)
            continue
        if not _has_extractable_text(text):
            warnings.warn(f"Skipping '{file_path}': {_NO_TEXT_MESSAGE}", stacklevel=2)
            continue
        source = file_path.relative_to(path).as_posix()
        chunks.extend(_chunk_document(source, text, chunk_size, chunk_overlap, suffix=suffix))
    return chunks


#: A named retrieval leg: `(name, fn)` where `fn(query_text, fetch_k)` returns
#: `(chunk index, raw score)` pairs, best first, at most `fetch_k` of them.
_Leg = Tuple[str, Callable[[str, int], List[Tuple[int, float]]]]

#: One fused candidate: `(chunk index, fused RRF score, {leg name: raw score})`.
_Candidate = Tuple[int, float, Dict[str, float]]


def _rrf_retrieve(
    query_variants: List[str],
    legs: List[_Leg],
    fetch_k: int,
) -> List[_Candidate]:
    """Run every (query_variant, leg) pair -- each leg returns a ranked list
    of `(chunk index, raw score)` pairs capped at fetch_k -- and fuse ALL
    resulting lists (variants x legs) with one unweighted
    `reciprocal_rank_fusion` call. Returns candidates ordered by fused score,
    descending, each carrying that fused score and the best raw score every
    leg gave the chunk across the variants (so the dict's keys say which legs
    surfaced it). A leg is a closure over one KB's own chunks/index (BM25
    scoring, or cosine scoring); parameterizing on the leg shape lets one
    function serve local_folder (1 leg), vector (1 leg), and hybrid (2 legs)
    identically. With exactly one variant and one leg this reproduces that
    leg's own order exactly (RRF over a single ranked list is
    order-preserving -- see the design spec's "Key facts")."""
    ranked_lists: List[List[int]] = []
    leg_scores: Dict[int, Dict[str, float]] = {}
    for variant in query_variants:
        for leg_name, leg in legs:
            scored = leg(variant, fetch_k)
            ranked_lists.append([idx for idx, _score in scored])
            for idx, score in scored:
                per_leg = leg_scores.setdefault(idx, {})
                if leg_name not in per_leg or score > per_leg[leg_name]:
                    per_leg[leg_name] = score
    fused = reciprocal_rank_fusion(*ranked_lists)
    return [
        (idx, score, leg_scores[idx])
        for idx, score in sorted(fused.items(), key=lambda pair: pair[1], reverse=True)
    ]


def _hit_from_candidate(chunks: List[_Chunk], candidate: _Candidate) -> RetrievalHit:
    idx, fused_score, leg_scores = candidate
    return RetrievalHit(chunk=chunks[idx], fused_score=fused_score, leg_scores=leg_scores)


def _report_expansion_usage(response: Any, model_spec: Any) -> None:
    """Meter the query-expansion call's tokens into the active tool-call
    context (`core/tool_context.py`), from which the adapter's tool loop
    forwards them onto the agent's `agent_completed` event.

    Entry shape mirrors `MemoryManager._usage_entry`, including its rule that
    only a string spec can be priced against the catalog (a `BaseChatModel`
    instance records tokens with `model=None`, leaving the cost null). A
    `fake:` model reports no `usage_metadata`, so it records nothing.
    """
    usage = getattr(response, "usage_metadata", None)
    if not usage:
        return
    add_usage(
        {
            "model": model_spec if isinstance(model_spec, str) else None,
            "input_tokens": usage.get("input_tokens", 0),
            "output_tokens": usage.get("output_tokens", 0),
        }
    )


def _query_variants(query: str, query_expansion_model: Any, query_expansion_count: int) -> List[str]:
    """`[query]` plus up to `query_expansion_count` LLM-generated alternative
    phrasings. Expansion failures/unset already degrade to `[]` inside
    `expand_query`, so this never raises and never returns an empty list."""
    expansions, response = expand_query(query_expansion_model, query, query_expansion_count)
    # A parse failure still returns the response: the call was billed either
    # way, so it is metered either way.
    _report_expansion_usage(response, query_expansion_model)
    return [query] + expansions


def _rerank_fetch_k(top_k: int, candidate_k: int, reranker: Optional[Reranker]) -> int:
    """How many pre-rerank candidates to fetch for this call. `candidate_k`
    is fixed at construction time from the constructor's default `top_k`, but
    a per-call `query(..., top_k=N)` can ask for more results than that --
    never fetch fewer than the effective `top_k`, or reranking would silently
    truncate below what was requested. Still bounded by
    `_MAX_RERANK_CANDIDATE_K`, so a very large per-call `top_k` cannot blow
    up the reranker batch size; in that case fewer than `top_k` results may
    come back, same as any other cost-bounded truncation."""
    if reranker is None:
        return top_k
    return min(max(top_k, candidate_k), _MAX_RERANK_CANDIDATE_K)


def _rerank_candidates(
    query: str,
    candidates: List[RetrievalHit],
    reranker: Optional[Reranker],
    top_k: int,
) -> List[RetrievalHit]:
    """Never mutates `candidates`. `candidates` is already sorted by
    retrieval rank (this function never reads their scores, only their order
    and `chunk.text`) and sliced to `candidate_k` by the caller. Empty input
    or no reranker configured is a pure slice -- no model call, no logging,
    `rerank_score` left `None`. Any exception during scoring (including a
    `_RerankScoringError` contract violation) falls back to the pre-rerank
    `candidates[:top_k]` slice, logged as a warning and again with no
    `rerank_score`: rerank is a quality layer, never a reason the knowledge
    base query itself fails. A successful rerank returns the hits in the
    cross-encoder's order, each carrying its score."""
    if reranker is None or not candidates:
        return candidates[:top_k]
    try:
        rerank_scores = reranker.score(query, [hit.chunk.text for hit in candidates])
    except Exception:
        _logger.warning("Rerank failed; falling back to retrieval order", exc_info=True)
        return candidates[:top_k]
    order = sorted(range(len(candidates)), key=lambda i: (-rerank_scores[i], i))
    return [candidates[i]._replace(rerank_score=float(rerank_scores[i])) for i in order[:top_k]]


# Trace bounds for a knowledge base tool call. The query is model-written
# text, so it needs the same length bound `_summarize()` gives every other
# trace field; the source list is ours, but a large `top_k` shouldn't turn one
# event into a wall of filenames.
_MAX_TRACE_QUERY_CHARS = 200
_MAX_TRACE_SOURCES = 10


def _trace_hit(hit: RetrievalHit) -> Dict[str, Any]:
    """One hit as the trace records it: citation, row identity, scores --
    rounded so ten of them stay a few hundred bytes -- and no chunk text."""
    return {
        "citation": _citation(hit.chunk),
        "chunk_id": hit.chunk.chunk_id,
        "document_id": hit.chunk.document_id,
        "fused_score": round(hit.fused_score, 4),
        "leg_scores": {name: round(score, 4) for name, score in hit.leg_scores.items()},
        "rerank_score": None if hit.rerank_score is None else round(hit.rerank_score, 4),
    }


def make_knowledge_base_tool(kb: KnowledgeBase) -> Callable[[str], str]:
    """Wrap a :class:`KnowledgeBase` as a single-argument agent tool.

    The returned callable's ``__name__`` matches ``kb.name``, so it can be
    referenced directly by name in a pipeline's ``tools:`` list — exactly
    like a built-in tool.

    The tool searches and formats separately (rather than calling
    ``kb.query()``, which is exactly those two steps) so it can report the
    retrieval to the run's trace: the query, how many chunks came back and
    which documents they came from. Byte-for-byte the same string is returned
    either way. The report travels via ``core/tool_context.py`` and is a no-op
    outside a run, and the ``__bestteam_tool_kind__`` marker tells the adapter
    this tool's ``tool_completed`` event is built from that report and never
    from a truncation of the result text — the documents an org indexed are
    not something a monitoring UI (or the ``trace_events`` table) should hold.
    """

    def _tool(query: str) -> str:
        search_hits = getattr(kb, "search_hits", None)
        if search_hits is not None:
            hits = search_hits(query)
            chunks = [hit.chunk for hit in hits]
        else:
            # A knowledge-base-shaped object from before `search_hits` existed
            # (a custom wrapper exposing only `search()`): still searchable,
            # still traced -- just with no scores to report, rather than
            # invented ones.
            hits = []
            chunks = kb.search(query)
        bounded_query = query[:_MAX_TRACE_QUERY_CHARS]
        # dict.fromkeys de-duplicates while keeping best-first order: several
        # chunks of one document cite it once.
        sources = list(dict.fromkeys(_citation(chunk) for chunk in chunks))[:_MAX_TRACE_SOURCES]
        report_trace(
            query=bounded_query,
            hit_count=len(chunks),
            sources=sources,
            # Every label the model was shown, in rank order and unbounded --
            # for the adapter's grounding check (core/grounding.py), which
            # must not mistake the eleventh passage's citation for an
            # invented one. `_kb_tool_trace_data` copies named fields only,
            # so this never reaches the trace event.
            citations=[_citation(chunk) for chunk in chunks],
            # The filename of each of those, as its own field. The check
            # verifies a filename-only tag against this set rather than
            # splitting a label at ", p." / " § " -- which misread a document
            # actually named that way, in both directions.
            citation_documents=[_citation_document(chunk) for chunk in chunks],
            # Which generation of the collection answered (None for a
            # folder-built KB), and per hit the row identity and the scores
            # behind its rank -- never the text. Bounded like `sources`.
            ingestion_job_id=getattr(kb, "ingestion_job_id", None),
            hits=[_trace_hit(hit) for hit in hits[:_MAX_TRACE_SOURCES]],
            summary=(
                f"{len(chunks)} result(s) for “{bounded_query}” — sources: {', '.join(sources)}"
                if chunks
                else f"No results for “{bounded_query}”"
            ),
        )
        return format_results(kb.name, query, chunks)

    _tool.__name__ = kb.name
    _tool.__bestteam_tool_kind__ = "knowledge_base"
    # The knowledge base's own one-line description, when it has one, is the
    # only thing telling the model WHICH collection answers a question -- an
    # org can have several, and their names alone rarely say.
    described = f": {kb.description}" if getattr(kb, "description", None) else ""
    _tool.__doc__ = (
        f"Search the '{kb.name}' knowledge base{described}. Use it whenever "
        "the question may be answered by these documents. Returns the most "
        'relevant excerpts, each tagged like "[source: handbook.pdf, p.3]". '
        "When you use an excerpt in your answer, cite it with that same "
        "[source: …] tag.\n\n"
        "Args:\n"
        "    query: The search query string.\n\n"
        "Returns:\n"
        "    Formatted text containing matching excerpts and their sources."
    )
    return _tool
