from __future__ import annotations

import logging
import re
import warnings
from abc import ABC, abstractmethod
from pathlib import Path
from typing import Any, Callable, List, NamedTuple, Optional

from ..exceptions import ConfigurationError
from ..tools import parse_file
from ..tools.file_parser import SUPPORTED_SUFFIXES as _SUPPORTED_SUFFIXES
from .fusion import expand_query, reciprocal_rank_fusion
from .reranking import (
    _MAX_RERANK_CANDIDATE_K,
    _resolve_candidate_k,
    Reranker,
    resolve_reranker,
)
from .text_tokenize import significant_terms, tokenize

_logger = logging.getLogger(__name__)

# Folder scanning discovers exactly what `parse_bytes` can dispatch on -- the
# same set `parse_file` supports, imported rather than copied so a suffix added
# to the parser is found here too, instead of silently not being. Re-exported
# under the old private name because `ui/backend/ingestion.py` imports it.

# Every parser in `bestteam.tools.file_parser` prefixes its output with a
# bracketed header line naming the document, and adds one per sheet/table
# inside it. Those lines are generated by us, not extracted from the document,
# so "the parsed string is non-empty" is not the same question as "the document
# had any text in it": a scanned PDF parses to `[PDF: scan.pdf -- 3 page(s)]`
# and nothing else, which chunks into a content-free chunk that matches
# nothing and tells nobody the pages were never read.
_PARSER_HEADER_RE = re.compile(r"^\[(?:PDF|Word|Excel|XML|Sheet|Table)[: ][^\n]*\]\s*$", re.M)

_NO_TEXT_MESSAGE = (
    "No text could be extracted from this file. If it is a scanned PDF it "
    "needs OCR, which isn't supported yet."
)


def _has_extractable_text(text: str) -> bool:
    """True when parsed `text` holds anything beyond the parser's own header
    lines -- i.e. the document actually contributed content."""
    return bool(_PARSER_HEADER_RE.sub("", text).strip())


def _unsupported_suffix_message(suffix: str) -> str:
    """The one wording both ingestion paths report for a file type neither
    `parse_file` nor `parse_bytes` can read."""
    supported = ", ".join(sorted(_SUPPORTED_SUFFIXES))
    return f"Unsupported file type '{suffix}'. Supported: {supported}"


def _require_bm25():
    """Check that rank_bm25 is available and return the BM25Okapi class.

    Raises ConfigurationError if the package is not installed.
    This check must run early to avoid expensive operations (like file parsing)
    before discovering a missing dependency.
    """
    try:
        from rank_bm25 import BM25Okapi
    except ImportError as exc:
        raise ConfigurationError(
            "Knowledge bases require the 'rank-bm25' package. "
            "Install it with: pip install 'bestteam[tools-rag]'"
        ) from exc
    return BM25Okapi


class KnowledgeBase(ABC):
    """A queryable source of client documents that agents can search.

    Implementations are responsible for ingesting documents from wherever
    they live and answering free-text queries with relevant excerpts.
    """

    name: str

    @abstractmethod
    def query(self, query: str, top_k: Optional[int] = None) -> str:
        """Return formatted excerpts most relevant to the query."""


class _Chunk(NamedTuple):
    source: str
    text: str


class LocalFolderKnowledgeBase(KnowledgeBase):
    """A knowledge base backed by a folder of documents on disk.

    Documents are parsed (via :func:`bestteam.tools.parse_file`), split into
    overlapping chunks, and indexed in memory with BM25 keyword search. This
    is intentionally lightweight — no embeddings, no vector store, no API
    keys — which suits the common case of a client handing over a folder
    with a handful to a couple dozen documents.
    """

    def __init__(
        self,
        name: str,
        path: str | Path,
        chunk_size: int = 1000,
        chunk_overlap: int = 100,
        top_k: int = 5,
        rerank_model: Any = None,
        candidate_k: Optional[int] = None,
        query_expansion_model: Any = None,
        query_expansion_count: int = 3,
    ) -> None:
        _require_bm25()
        _validate_chunk_params(name, chunk_size, chunk_overlap)
        self.path = Path(path)
        chunks = _load_document_chunks(self.path, chunk_size, chunk_overlap)
        self._init_from_chunks(
            name, chunks, top_k,
            rerank_model=rerank_model,
            candidate_k=candidate_k,
            query_expansion_model=query_expansion_model,
            query_expansion_count=query_expansion_count,
        )

    @classmethod
    def from_chunks(
        cls,
        name: str,
        chunks: List["_Chunk"],
        top_k: int = 5,
        rerank_model: Any = None,
        candidate_k: Optional[int] = None,
        query_expansion_model: Any = None,
        query_expansion_count: int = 3,
    ) -> "LocalFolderKnowledgeBase":
        """Build directly from pre-parsed chunks, skipping the file-parsing
        pipeline. Used by the backend's DB-backed ingestion path (see
        ui/backend/knowledge_bases.py) -- the SDK itself never touches a
        database; chunks are handed in as plain data."""
        self = cls.__new__(cls)
        self.path = None
        self._init_from_chunks(
            name, chunks, top_k,
            rerank_model=rerank_model,
            candidate_k=candidate_k,
            query_expansion_model=query_expansion_model,
            query_expansion_count=query_expansion_count,
        )
        return self

    def _init_from_chunks(
        self,
        name: str,
        chunks: List["_Chunk"],
        top_k: int,
        *,
        rerank_model: Any = None,
        candidate_k: Optional[int] = None,
        query_expansion_model: Any = None,
        query_expansion_count: int = 3,
    ) -> None:
        BM25Okapi = _require_bm25()

        self.name = name
        self.default_top_k = top_k
        self._reranker = resolve_reranker(rerank_model) if rerank_model is not None else None
        if candidate_k is not None and (candidate_k < top_k or candidate_k > _MAX_RERANK_CANDIDATE_K):
            raise ConfigurationError(
                f"Knowledge base '{name}': candidate_k ({candidate_k}) must be "
                f"between top_k ({top_k}) and {_MAX_RERANK_CANDIDATE_K}"
            )
        self._candidate_k = _resolve_candidate_k(candidate_k, top_k)
        self.query_expansion_model = query_expansion_model
        self.query_expansion_count = query_expansion_count

        self._chunks = list(chunks)
        if not self._chunks:
            raise ConfigurationError(
                f"Knowledge base '{name}' has no readable documents"
                + (f" in {self.path}" if self.path is not None else "")
            )

        self._chunk_tokens = [tokenize(chunk.text) for chunk in self._chunks]
        self._chunk_terms = [significant_terms(tokens) for tokens in self._chunk_tokens]
        self._bm25 = BM25Okapi(self._chunk_tokens)

    def _bm25_leg(self, query_text: str, fetch_k: int) -> List[int]:
        """Identical scoring logic to the pre-refactor `query()` body,
        returning chunk indices instead of `(score, chunk)` tuples."""
        query_tokens = tokenize(query_text)
        query_terms = significant_terms(query_tokens)
        scores = self._bm25.get_scores(query_tokens)

        matches = [
            (len(query_terms & chunk_terms), score, idx)
            for idx, (score, chunk_terms) in enumerate(zip(scores, self._chunk_terms))
            if query_terms & chunk_terms
        ]
        matches.sort(key=lambda m: (m[0], m[1]), reverse=True)
        return [idx for _overlap, _score, idx in matches[:fetch_k]]

    def query(self, query: str, top_k: Optional[int] = None) -> str:
        top_k = top_k or self.default_top_k
        variants = _query_variants(query, self.query_expansion_model, self.query_expansion_count)
        fetch_k = _rerank_fetch_k(top_k, self._candidate_k, self._reranker)
        ranked_indices = _rrf_retrieve(variants, [self._bm25_leg], fetch_k)
        # The score half of each tuple is a synthetic rank-derived placeholder,
        # not a real retrieval score -- RRF has already re-ordered by fused
        # rank, and _rerank_candidates only reads candidate order/chunk.text.
        results = [(float(-i), self._chunks[idx]) for i, idx in enumerate(ranked_indices[:fetch_k])]
        results = _rerank_candidates(query, results, self._reranker, top_k)

        if not results:
            return f"No results found in knowledge base '{self.name}' for: {query}"

        lines = [f"Knowledge base '{self.name}' results for: {query}\n"]
        for i, (_score, chunk) in enumerate(results, 1):
            lines.append(f"{i}. [source: {chunk.source}]")
            lines.append(chunk.text.strip())
            lines.append("")
        return "\n".join(lines)


_DEFAULT_SEPARATORS = ["\n\n", "\n", "。", "！", "？", ". ", " ", ""]

_MARKDOWN_SEPARATORS = ["\n# ", "\n## ", "\n### ", "\n#### ", "\n\n", "\n", "。", "！", "？", ". ", " ", ""]

_XML_TOP_LEVEL_BOUNDARY = re.compile(r"(?=\n  <)")

# Separators that mark the START of the content they introduce (a heading
# line) rather than the END of what precedes them (like sentence-terminating
# punctuation) -- these get reattached as a prefix on the following piece;
# everything else is reattached as a suffix on the preceding piece.
_PREFIX_SEPARATORS = {"\n# ", "\n## ", "\n### ", "\n#### "}


def _separators_for_suffix(suffix: str) -> List[str]:
    return _MARKDOWN_SEPARATORS if suffix == ".md" else _DEFAULT_SEPARATORS


def _pack_pieces(pieces: List[str], chunk_size: int, fallback_separators: List[str]) -> List[str]:
    """Greedily merge adjacent pieces up to chunk_size; recurse into
    fallback_separators for any individual piece that's still too large on
    its own, folding whatever's accumulated in `current` (often a short
    heading/tag) into the text being split, so it always ends up packed
    with content rather than stranded as its own content-free chunk."""
    results: List[str] = []
    current = ""
    for piece in pieces:
        candidate = current + piece
        if len(candidate) <= chunk_size:
            current = candidate
        elif len(piece) > chunk_size:
            # Split `current + piece` as one text rather than `piece` alone,
            # so whatever's accumulated in `current` (often a short
            # heading/tag) gets packed together with as much of the
            # oversized piece as fits, instead of being left to fend for
            # itself as a separate, content-free chunk.
            sub = _recursive_split(current + piece, fallback_separators, chunk_size)
            results.extend(sub)
            current = ""
        else:
            if current:
                results.append(current)
            current = piece
    if current:
        results.append(current)
    return results


def _recursive_split(text: str, separators: List[str], chunk_size: int) -> List[str]:
    """Split text on the coarsest separator that fits chunk_size, recursing
    into finer separators only for pieces that are still too large."""
    if len(text) <= chunk_size:
        return [text] if text else []
    if not separators or separators[0] == "":
        # Last resort: no separator left to split on. Balance the split
        # evenly across the minimum number of chunks that fit chunk_size,
        # rather than greedily packing char-by-char at a fixed offset --
        # greedy fixed-size packing can strand a tiny (even single-character)
        # remainder as its own chunk, e.g. a lone trailing punctuation mark.
        length = len(text)
        num_chunks = -(-length // chunk_size)
        size = -(-length // num_chunks)
        return [text[i : i + size] for i in range(0, length, size)]

    sep, *rest = separators
    raw_pieces = text.split(sep)
    if sep in _PREFIX_SEPARATORS:
        # Re-attach the separator to every piece but the first, so a
        # piece that ends up starting its own chunk still carries its
        # own marker (e.g. a Markdown "## Heading") instead of silently
        # losing it.
        pieces = [raw_pieces[0]] + [sep + p for p in raw_pieces[1:]]
    else:
        # Suffix-style separators (sentence terminators, paragraph/line
        # breaks) end the piece before them, not start the piece after
        # -- re-attaching them as a prefix would strand a lone
        # punctuation mark as its own chunk when the split lands there.
        pieces = [p + sep for p in raw_pieces[:-1]] + [raw_pieces[-1]]
    return _pack_pieces(pieces, chunk_size, rest)


def _apply_overlap(pieces: List[str], chunk_overlap: int, chunk_size: int) -> List[str]:
    """Prepend each chunk (after the first) with up to chunk_overlap trailing
    characters of the previous chunk, capped so no chunk ever exceeds
    chunk_size -- the piece's own content is never trimmed, only how much
    cross-boundary context gets borrowed shrinks (down to zero) when a piece
    is already at or near chunk_size.

    Note: the borrowed prefix is a raw character slice, not separator-aware
    -- it can land mid-word/mid-tag/mid-heading. Structure-aware splitting
    (this module's main feature) applies to how chunks are cut, not to the
    overlap glued onto their boundaries."""
    if chunk_overlap <= 0 or len(pieces) <= 1:
        return pieces
    result = [pieces[0]]
    for prev, piece in zip(pieces, pieces[1:]):
        available = max(0, min(chunk_overlap, chunk_size - len(piece)))
        result.append(prev[-available:] + piece if available else piece)
    return result


def _chunk_text(text: str, chunk_size: int, chunk_overlap: int, suffix: str = "") -> List[str]:
    """Split text into chunks, preferring the document's own structure
    (paragraphs, sentences, words) over blind fixed-size character cuts."""
    text = text.strip()
    if not text:
        return []
    if suffix == ".xml":
        sections = _XML_TOP_LEVEL_BOUNDARY.split(text)
        pieces = _pack_pieces(sections, chunk_size, _DEFAULT_SEPARATORS)
    else:
        pieces = _recursive_split(text, _separators_for_suffix(suffix), chunk_size)
    pieces = [p for p in pieces if p.strip()]
    return _apply_overlap(pieces, chunk_overlap, chunk_size)


def _validate_chunk_params(name: str, chunk_size: int, chunk_overlap: int) -> None:
    if chunk_size <= 0:
        raise ConfigurationError(
            f"Knowledge base '{name}': chunk_size must be positive, got {chunk_size}"
        )
    if chunk_overlap < 0 or chunk_overlap >= chunk_size:
        raise ConfigurationError(
            f"Knowledge base '{name}': chunk_overlap ({chunk_overlap}) must be "
            f"non-negative and less than chunk_size ({chunk_size})"
        )


def _load_document_chunks(path: Path, chunk_size: int, chunk_overlap: int) -> List[_Chunk]:
    chunks: List[_Chunk] = []
    for file_path in sorted(path.rglob("*")):
        if not file_path.is_file():
            continue
        suffix = file_path.suffix.lower()
        if suffix not in _SUPPORTED_SUFFIXES:
            warnings.warn(
                f"Skipping '{file_path}': {_unsupported_suffix_message(suffix)}",
                stacklevel=2,
            )
            continue
        try:
            text = parse_file(str(file_path))
        except ConfigurationError as exc:
            warnings.warn(f"Skipping unreadable file '{file_path}': {exc}", stacklevel=2)
            continue
        except Exception as exc:
            warnings.warn(f"Skipping unreadable file '{file_path}': {exc}", stacklevel=2)
            continue
        if not _has_extractable_text(text):
            warnings.warn(f"Skipping '{file_path}': {_NO_TEXT_MESSAGE}", stacklevel=2)
            continue
        source = file_path.relative_to(path).as_posix()
        for piece in _chunk_text(text, chunk_size, chunk_overlap, suffix=suffix):
            chunks.append(_Chunk(source=source, text=piece))
    return chunks


def _rrf_retrieve(
    query_variants: List[str],
    legs: List[Callable[[str, int], List[int]]],
    fetch_k: int,
) -> List[int]:
    """Run every (query_variant, leg) pair -- each leg returns a ranked list
    of chunk indices capped at fetch_k -- and fuse ALL resulting lists
    (variants x legs) with one unweighted `reciprocal_rank_fusion` call.
    Returns chunk indices ordered by fused score, descending. A leg is a
    closure over one KB's own chunks/index (BM25 scoring, or cosine
    scoring); parameterizing on `(query_text, fetch_k) -> List[int]` lets
    one function serve local_folder (1 leg), vector (1 leg), and hybrid (2
    legs) identically. With exactly one variant and one leg this reproduces
    that leg's own order exactly (RRF over a single ranked list is
    order-preserving -- see the design spec's "Key facts")."""
    ranked_lists = [leg(variant, fetch_k) for variant in query_variants for leg in legs]
    fused = reciprocal_rank_fusion(*ranked_lists)
    return [idx for idx, _score in sorted(fused.items(), key=lambda pair: pair[1], reverse=True)]


def _query_variants(query: str, query_expansion_model: Any, query_expansion_count: int) -> List[str]:
    """`[query]` plus up to `query_expansion_count` LLM-generated alternative
    phrasings. Expansion failures/unset already degrade to `[]` inside
    `expand_query`, so this never raises and never returns an empty list."""
    expansions, _response = expand_query(query_expansion_model, query, query_expansion_count)
    return [query] + expansions


def _rerank_fetch_k(top_k: int, candidate_k: int, reranker: Optional[Reranker]) -> int:
    """How many pre-rerank candidates to fetch for this call. `candidate_k`
    is fixed at construction time from the constructor's default `top_k`, but
    a per-call `query(..., top_k=N)` can ask for more results than that --
    never fetch fewer than the effective `top_k`, or reranking would silently
    truncate below what was requested. Still bounded by
    `_MAX_RERANK_CANDIDATE_K`, so a very large per-call `top_k` cannot blow
    up the reranker batch size; in that case fewer than `top_k` results may
    come back, same as any other cost-bounded truncation."""
    if reranker is None:
        return top_k
    return min(max(top_k, candidate_k), _MAX_RERANK_CANDIDATE_K)


def _rerank_candidates(
    query: str,
    candidates: List["tuple[float, _Chunk]"],
    reranker: Optional[Reranker],
    top_k: int,
) -> List["tuple[float, _Chunk]"]:
    """Never mutates `candidates`. `candidates` is already sorted by
    retrieval rank (the score half of each tuple may be a synthetic
    placeholder, not a real score -- this function never reads it) and
    sliced to `candidate_k` by the caller. Empty input or no reranker
    configured is a pure slice -- no model call, no logging. Any exception
    during scoring (including a `_RerankScoringError` contract violation)
    falls back to the pre-rerank `candidates[:top_k]` slice, logged as a
    warning: rerank is a quality layer, never a reason the knowledge base
    query itself fails."""
    if reranker is None or not candidates:
        return candidates[:top_k]
    try:
        rerank_scores = reranker.score(query, [chunk.text for _score, chunk in candidates])
    except Exception:
        _logger.warning("Rerank failed; falling back to retrieval order", exc_info=True)
        return candidates[:top_k]
    order = sorted(range(len(candidates)), key=lambda i: (-rerank_scores[i], i))
    return [candidates[i] for i in order[:top_k]]


def make_knowledge_base_tool(kb: KnowledgeBase) -> Callable[[str], str]:
    """Wrap a :class:`KnowledgeBase` as a single-argument agent tool.

    The returned callable's ``__name__`` matches ``kb.name``, so it can be
    referenced directly by name in a workflow's ``tools:`` list — exactly
    like a built-in tool.
    """

    def _tool(query: str) -> str:
        return kb.query(query)

    _tool.__name__ = kb.name
    _tool.__doc__ = (
        f"Search the '{kb.name}' knowledge base for information relevant to "
        "the query. Returns the most relevant document excerpts along with "
        "the source file each excerpt came from.\n\n"
        "Args:\n"
        "    query: The search query string.\n\n"
        "Returns:\n"
        "    Formatted text containing matching excerpts and their sources."
    )
    return _tool
